import Head from "next/head";
import Image from "next/image";
import BtnPrimary from '@/components/buttons/BtnPrimary'
import BtnOrange from '@/components/buttons/BtnOrange'
import BtnLight from '@/components/buttons/BtnLight'

import { useRouter } from "next/router";

export default function Home() {

  const router = useRouter()

  return (
    <>
      <Head>
        <title>Home | Certify</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="manifest" href="/site.webmanifest" />
        <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5" />
        <meta name="msapplication-TileColor" content="#da532c" />
        <meta name="theme-color" content="#ffffff" />
      </Head>
      <main className="grid gap-5 place-content-center h-screen">
          <BtnPrimary
            btnText='Sign In'
            btnOnClick={() => router.push('/signin')}
          />
          <BtnOrange
            btnText='Dashboard'
            btnOnClick={() => router.push('/app')}
          />
          <BtnLight
            btnText='Something Else'
            btnOnClick={() => router.push('/something-else')}
          />
      </main>
    </>
  );
}
