import Head from 'next/head'
import Container from '@/components/Container'
import PageSpacing from '@/components/PageSpacing'
import Header from '@/components/Header'
import BtnPrimary from '@/components/buttons/BtnPrimary'

import { useRouter } from 'next/router'

export default function Home() {
  const router = useRouter()

  return (
    <>
      <Head>
        <title>Home | Certify</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
        <link
          rel="manifest"
          href="/site.webmanifest"
        />
        <link
          rel="mask-icon"
          href="/safari-pinned-tab.svg"
          color="#5bbad5"
        />
        <meta
          name="msapplication-TileColor"
          content="#da532c"
        />
        <meta
          name="theme-color"
          content="#ffffff"
        />
      </Head>
      <main>
        <PageSpacing>
          <Container>
            <Header
              h1Text="Welcome to Certify"
              className="items-center text-center"
            />
            <div className="grid grid-cols-1 items-center justify-center gap-3 sm:grid-cols-2 md:grid-cols-3">
              <BtnPrimary
                btnText="Register"
                width="w-full"
                btnOnClick={() =>
                  router.push('/register')
                }
              />
              <BtnPrimary
                btnText="Sign In"
                width="w-full"
                btnOnClick={() =>
                  router.push('/signin')
                }
              />
              <BtnPrimary
                btnText="Dashboard"
                width="w-full"
                btnOnClick={() =>
                  router.push('/app')
                }
              />
            </div>
          </Container>
        </PageSpacing>
      </main>
    </>
  )
}
