import Head from 'next/head'
import Container from '@/components/ContentAlignment/Container'
import { H1 } from '@/components/Headings'
import Button from '@/components/Button'
import { useRouter } from 'next/router'
import Nav from '@/components/ContentAlignment/Frame/Nav'

export default function Home() {
  const router = useRouter()
  return (
    <>
      <Head>
        <title>Home | Certify</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
        <link rel="manifest" href="/site.webmanifest" />
        <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5" />
        <meta name="msapplication-TileColor" content="#da532c" />
        <meta name="theme-color" content="#ffffff" />
      </Head>
      <Nav />
      <Container className="flex h-screen items-center justify-center">
        <div className="flex flex-col items-center justify-center gap-4">
          <H1>Welcome to Certify</H1>
          <div className="flex flex-wrap">
            <Button width="w-32" onClick={() => router.push('/signin')}>
              Sign In
            </Button>
          </div>
        </div>
      </Container>
    </>
  )
}
